site_name: Документация Masonite
theme:
  name: material
  features:
    - navigation.instant
#    - navigation.sections
  logo: assets/masonite.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: red
      toggle:
        icon: material/lightbulb
        name: Выключить свет

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Включить свет
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MasoniteFramework/masonite
    - icon: fontawesome/brands/telegram
      link: https://t.me/masonite_channel
nav:
  - Введение и установка: index.md
  - Примеры:
      - ToDo:
        - Установка: examples/todo/installation.md
        - Структура проекта: examples/todo/structure_masonite.md
        - Работа с базой данных: examples/todo/database_architecture.md
        - Категории: examples/todo/category.md
        - Задачи: examples/todo/task.md
  - Основное:
    - Маршрутизация (Route): basics/routing.md
    - Контроллеры (Controllers): basics/controllers.md
    - Middleware: basics/middleware.md
    - Response: basics/response.md
    - Request: basics/request.md
    - Статические файлы: basics/static_files.md
    - Представления (View): basics/view.md
    - Environments: basics/environments.md
    - Конфигурация: basics/configuration.md
    - Обработка ошибок: basics/error_handling.md
  - Особенности:
    - Разработка API: feature/api.md
    - Аутентификация: feature/authentication.md
    - Авторизация: feature/authorization.md
    - Трансляция событий: feature/broadcasting.md
    - Кэширование: feature/caching.md
    - Сборка assets: feature/compiling-assets.md
    - Команды: feature/commands.md
  - Архитектура:
    - Service Provider: architecture/service-provider.md
    - Service Container: architecture/service-container.md

