site_name: Документация Masonite
theme:
  name: material
  features:
    - navigation.instant
  logo: assets/masonite.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: red
      toggle:
        icon: material/lightbulb
        name: Выключить свет

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Включить свет
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MasoniteFramework/masonite
    - icon: fontawesome/brands/telegram
      link: https://t.me/masonite_channel
nav:
  - Введение и установка: index.md
  - Примеры:
      - ToDo: examples/masonite-todo.md
  - Основное:
    - Маршрутизация (Route): basics/routing.md
    - Контроллеры (Controllers): basics/controllers.md
    - Middleware: basics/middleware.md
    - Response: basics/response.md
    - Request: basics/request.md
    - Статические файлы: basics/static_files.md
    - Представления (View): basics/view.md
    - Environments: basics/environments.md
    - Конфигурация: basics/configuration.md
    - Обработка ошибок: basics/error_handling.md
  - Архитектура:
    - Service Container: architecture/service-container.md
